version: '3.8'

services:
  9router:
    image: decolua/9router:latest
    container_name: 9router
    ports:
      - "20128:20128"
      - "443:443"
    volumes:
      - 9router-data:/app/data
    restart: unless-stopped

  hermes-agent:
    image: nousresearch/hermes-agent:latest
    container_name: hermes-agent
    command: gateway run
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=sk_9router
      - GATEWAY_ALLOW_ALL_USERS=true

    volumes:
      - hermes-data:/opt/data
      - ./config.yaml:/opt/data/config.yaml
      - ./.env:/opt/data/.env


    restart: unless-stopped
    depends_on:
      - 9router


volumes:
  9router-data:
  hermes-data:
